import Head from 'next/head'

import Banner from "../components/Banner";
import Layout from "../components/Layout";
import Products from "../components/Products";
import cwp from "../public/img/products/isolate/Chocolate_Wheyprotein.png";

const mainBanner = {
  asset: cwp,
  title: "Proteina",
  copy: "Para mejores resultados en tiempo record.",
  cta: "Comprar",
  bgcolor: "#3312f9",
  size: "med",
  order: "rtl",
};


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App SSR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Banner data={mainBanner} />
        <Products />
      </Layout>
    </div>
  )
}


/**
 *
 * Los productos serán almacenados de manera local y consumidos desde un único archivo JSON
Cada producto debe poseer:
Nombre
Descripción
Precio
Al menos una Imagen
Cantidad Disponible
 */